// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/flux-standard-action/flux-standard-action.d.ts
declare module "flux-standard-action" {
    export interface ErrorAction extends Action<Error> {
        error: boolean;
    }

    export interface Action<T> {
        type: string;
        payload?: T;
        error?: boolean;
    }

    // Usage: var action: Action<sring> & AnyMeta;
    export interface AnyMeta {
        meta: any
    }

    // Usage: var action: Action<sring> & TypedMeta<string>;
    export interface TypedMeta<T> {
        meta: T
    }

    export function isFSA(action: any): boolean;

    export function isError(action: any): boolean;
}
